#!/usr/bin/python3
# This code write by Ms.nope
# Setuping mathint package!
import platform
import os
import time
import sys
###############################################################
system = platform.uname()[0]
# setup on Linuxx
if system == 'Linux':
  os.system("sudo apt install python")
  os.system("sudo apt install python3")
  os.system("chmod a+x mathint.py")
  os.system("chmod +x uninstall.sh")
  os.system("sudo cp mathint.py /usr/local/bin")
  os.system("sudo cp mathint.py /usr/lib/python3.6")
  os.system("sudo cp .mathint /usr/local")
  os.system("cd .. && sudo cp mathint /usr/share")
  time.sleep(2)
  print("Finish!")
  sys.exit()
# setup on Windows
elif system == 'Win32':
    os.system("pip install --upgtade pip")
    print("Finish!")
    sys.exit()
# setup on Mac Os
elif system == 'Mac':
    os.system("sudo apt install python")
    os.system("sudo apt install python3")
    os.system("chmod a+x mathint")
    os.system("chmod +x uninstall.sh")
    os.system("sudo cp mathint.py /usr/local/bin")
    os.system("sudi cp mathint.py /usr/lib/python3.6")
    time.sleep(2)
    print("Finish!")
    sys.exit()
# This programm run on: Linux,Windows,MacOs
else:
    print("\nThis programm run as : Windows,Linux,MacOs Platform!\n")
    sys.exit()
