#!/usr/bin/python3
# This code write by Ms.nope
import os
import time
import sys
import platform
system = platform.uname()[0]
if system == 'Linux':
  os.system("cd /usr/local/bin && sudo rm mathint.py")
  os.system("cd /usr/lib/python3.6 && sudo rm mathint.py")
  print("Uninstalling..., Finish!")
  time.sleep(2)
  sys.exit()
elif system == 'Mac':
    os.system("cd /usr/local/bin && sudo rm mathint.py")
    print("Uninstalling..., Finish!")
    time.sleep(2)
    sys.exit()
else:
    print(" ")
    sys.exit()
